// Generated by brainfuck compiler

package main

import (
	"bufio"
	"os"
)

func main() {

	memory := []rune{}
	cursor := 0

	for i := 0; i < 30000; i++ {
		memory = append(memory, 0)
	}

    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    for memory[cursor] != 0 {
        cursor++
        memory[cursor]++
        memory[cursor]++
        memory[cursor]++
        memory[cursor]++
        for memory[cursor] != 0 {
            cursor++
            memory[cursor]++
            memory[cursor]++
            cursor++
            memory[cursor]++
            memory[cursor]++
            memory[cursor]++
            cursor++
            memory[cursor]++
            memory[cursor]++
            memory[cursor]++
            cursor++
            memory[cursor]++
            cursor--
            cursor--
            cursor--
            cursor--
            memory[cursor]--
            }
        cursor++
        memory[cursor]++
        cursor++
        memory[cursor]++
        cursor++
        memory[cursor]--
        cursor++
        cursor++
        memory[cursor]++
        for memory[cursor] != 0 {
            cursor--
            }
        cursor--
        memory[cursor]--
        }
    cursor++
    cursor++
    print(string(memory[cursor]))
    cursor++
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    print(string(memory[cursor]))
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    print(string(memory[cursor]))
    print(string(memory[cursor]))
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    print(string(memory[cursor]))
    cursor++
    cursor++
    print(string(memory[cursor]))
    cursor--
    memory[cursor]--
    print(string(memory[cursor]))
    cursor--
    print(string(memory[cursor]))
    memory[cursor]++
    memory[cursor]++
    memory[cursor]++
    print(string(memory[cursor]))
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    print(string(memory[cursor]))
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    memory[cursor]--
    print(string(memory[cursor]))
    cursor++
    cursor++
    memory[cursor]++
    print(string(memory[cursor]))
    cursor++
    memory[cursor]++
    memory[cursor]++
    print(string(memory[cursor]))
}

func input() rune {
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')
	return rune([]byte(input)[0])
}
